cluster=cloud-infra-layer
zone=us-east1-c
project=sonic-column-220616
# project=cloudinfra-219900
image=gcr.io/$project/dloncloud
cpu_machine=n1-standard-1
cpu_nodes=1
gpu_machine=n1-standard-1
gpu_type=nvidia-tesla-k80
gpu_nodes=4
gpu_per_node=1
gpu_max_nodes=4